from CommunityDetection.Communities import Communities, get_community_folder_path
from CommunityDetection.Community import Community
from CommunityDetection.BaseCommunityDetection import BaseCommunityDetection
from CommunityDetection.QUBOBipartiteCommunityDetection import QUBOBipartiteCommunityDetection
from CommunityDetection.QUBOBipartiteProjectedCommunityDetection import QUBOBipartiteProjectedCommunityDetection
from CommunityDetection.QUBOCommunityDetection import QUBOCommunityDetection
from CommunityDetection.CommunityDetectionRecommender import CommunityDetectionRecommender


class EmptyCommunityError(Exception):
    pass
